import Foundation
import Ignite

struct MainLayout: Layout {
    @Environment(\.page) var page
    
    @MainActor var body: some Document {
        PlainDocument {
            Head {
                // Essential meta tags for SEO and functionality (viewport, description, author are auto-generated by Ignite)
                MetaTag(name: "keywords", content: "iOS, accessibility, a11y, Swift, VoiceOver, development")
                
                // Enhanced meta tags for better SEO and social sharing
                MetaTag(name: "robots", content: "index, follow, max-snippet:-1, max-image-preview:large")
                MetaTag(name: "googlebot", content: "index, follow")
                
                // Canonical URL to prevent duplicate content issues
                MetaLink(href: "https://accessibilityupto11.com\(page.url.path)", rel: "canonical")
                
                // Global Open Graph meta tags for SEO and social sharing (og:title, og:description, og:site_name, twitter:title, twitter:card are auto-generated by Ignite)
                MetaTag(property: "og:type", content: "website")
                MetaTag(property: "og:url", content: "https://accessibilityupto11.com")
                MetaTag(property: "og:image", content: "https://accessibilityupto11.com/Images/Site/Global/LogoShare.png")
                MetaTag(property: "og:image:alt", content: "Accessibility up to 11! Logo")
                MetaTag(property: "og:locale", content: "en_US")
                
                // Global Twitter Card meta tags
                MetaTag(name: "twitter:image", content: "https://accessibilityupto11.com/Images/Site/Global/LogoShare.png")
                MetaTag(name: "twitter:image:alt", content: "Accessibility up to 11! Logo")
                MetaTag(name: "twitter:site", content: "@dadederk")
                MetaTag(name: "twitter:creator", content: "@dadederk")
                
                // Custom CSS for navigation and theme support
                MetaLink(href: "/custom-navigation.css", rel: "stylesheet")

                // Redirect from GitHub Pages to custom domain for SEO
                Script(code: """
                    // Immediate redirect from dadederk.github.io to accessibilityupto11.com
                    (function() {
                        if (window.location.hostname === 'dadederk.github.io') {
                            // Redirect to about page for personal branding
                            window.location.replace('https://accessibilityupto11.com/about');
                        }
                    })();
                """)
                
                // Set theme data attributes for Ignite's theme switching JavaScript
                Script(code: """
                    // Set theme data attributes immediately
                    document.documentElement.setAttribute('data-light-theme', 'accessibility-up-to11-light');
                    document.documentElement.setAttribute('data-dark-theme', 'accessibility-up-to11-dark-dark');

                    // Apply theme immediately based on system preference
                    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                    const themeID = prefersDark ? 'accessibility-up-to11-dark-dark' : 'accessibility-up-to11-light';
                    document.documentElement.setAttribute('data-bs-theme', themeID);

                    // Apply syntax highlighting theme immediately
                    const syntaxTheme = getComputedStyle(document.documentElement)
                        .getPropertyValue('--syntax-highlight-theme').trim().replace(/"/g, '');
                    if (syntaxTheme) {
                        document.querySelectorAll('link[data-highlight-theme]').forEach(link => {
                            link.setAttribute('disabled', 'disabled');
                        });
                        const themeLink = document.querySelector(`link[data-highlight-theme="${syntaxTheme}"]`);
                        if (themeLink) {
                            themeLink.removeAttribute('disabled');
                        }
                    }
                    """)
            }
            
            Body {
                // Header - Custom LogoNavBar component
                LogoNavBar()
                
                // Main content area
                Section {
                    content
                }
                .id("main-content")
                .padding()
                .style(.paddingBottom, "80px")

                
                // Footer - Fixed bottom implementation
                Section {
                    HStack(alignment: .center) {
                        Text {
                            "Created in Swift with "
                            Link("Ignite.", target: "https://github.com/twostraws/Ignite")
                        }
                        
                        Link(target: "https://swiftforswifts.org") {
                            Image(decorative: "https://swiftforswifts.org/downloads/swift-for-swifts-icon.png")
                                .resizable()
                                .frame(height: .em(2.0))
                                .style(.objectFit, "contain")
                                .style(.aspectRatio, "1 / 1")
                        }
                        
                        Link("Supporting Swift for Swifts", target: "https://swiftforswifts.org/")
                            .target(.newWindow)
                            .relationship(.noOpener)
                    }
                    .style(.justifyContent, "center")
                }
                .position(.fixedBottom)
                .style(.backgroundColor, "var(--bs-secondary-bg)")
                .border(.gray, edges: .top)
                .ignorePageGutters()
                .class("text-center", "py-3")
            }
            .data("current-page", page.url.path)
        }
    }
}
