import Foundation

/// Curated 365 Days topic titles (generated from `Days365Content/recommended-titles.md`).
enum RecommendedTitles {
    static let byDay: [Int: String] = [
        0: "Are you up for 365 days of iOS accessibility?",
        1: "UIAccessibility: label, value, trait, and hint",
        2: "SwiftUI accessibility modifiers match UIKit",
        3: "What makes a good accessibilityLabel",
        4: "Don't put the control type in accessibilityLabel",
        5: "Label image-only buttons for VoiceOver",
        6: "Attributed accessibility labels are a thing",
        7: "Multilingual labels with speech attributes",
        8: "Fix pronunciation with accessibilitySpeechIPANotation",
        9: "IPA for homographs and your app name",
        10: "IPA notation so VoiceOver says paella right",
        11: "Emphasize labels with accessibilitySpeechPitch",
        12: "Spell out codes with accessibilitySpeechSpellOut",
        13: "Speak punctuation with accessibilitySpeechPunctuation",
        14: "Don't break Voice Control when tweaking labels",
        15: "Use formatters for abbreviation labels",
        16: "Better relative date and weekday labels",
        17: "Detect when VoiceOver is running",
        18: "Add a label to custom loading indicators",
        19: "WWDC22 kicks off with accessibility news",
        20: "What accessibility traits tell VoiceOver users",
        21: "Combine multiple accessibility traits",
        22: "The button accessibility trait in VoiceOver",
        23: "Add the button trait to table cells",
        24: "Disclosure indicators add the button trait",
        25: "Configure button trait on custom controls",
        26: "Meet the VoiceOver rotor",
        27: "Header trait speeds up VoiceOver navigation",
        28: "Header trait is an easy accessibility win",
        29: "The link accessibility trait",
        30: "Embedded links in UITextView with VoiceOver",
        31: "Hacks are accessibility's worst enemy",
        32: "Adjustable trait for custom value controls",
        33: "Implement accessibilityIncrement and Decrement",
        34: "Meaningful accessibilityValue for sliders",
        35: "searchField trait for custom search bars",
        36: "updatesFrequently for live changing content",
        37: "selected trait announces before the label",
        38: "notEnabled trait for disabled controls",
        39: "Tune VoiceOver slider adjustment increments",
        40: "Playing piano with VoiceOver: allowsDirectInteraction",
        41: "keyboardKey trait for custom keypads",
        42: "tabBar trait for custom tab bars",
        43: "image trait unlocks Image Explorer",
        44: "Mark decorative images as non-accessible",
        45: "startsMediaSession avoids label repetition",
        46: "playsSound for buttons with sound effects",
        47: "summaryElement announces on app launch",
        48: "accessibilityValue conveys control state",
        49: "Manage traits with Swift OptionSet",
        50: "Labels, traits, and values for the same experience",
        51: "Apple's guidelines for accessibilityHint",
        52: "UIColor accessibilityName for color labels",
        53: "Handle VoiceOver double tap with accessibilityActivate",
        54: "Convey state with color, haptics, and icons",
        55: "Include icon state in labels and values",
        56: "Override labels for NSTextAttachment icons",
        57: "Text and background color contrast matters",
        58: "Meet Apple's 44×44 minimum tap targets",
        59: "Please don't use accessibility labels as UI test IDs",
        60: "Implement Magic Tap with accessibilityPerformMagicTap",
        61: "Dismiss with accessibilityPerformEscape",
        62: "isAccessibilityElement hides child elements",
        63: "Group cells for faster VoiceOver navigation",
        64: "Reach grouped buttons with custom actions",
        65: "Custom actions for hidden swipe gestures",
        66: "Reduce clutter by grouping with custom actions",
        67: "Custom actions work in Switch Control",
        68: "Add images to UIAccessibilityCustomAction",
        69: "Custom actions with Full Keyboard Access",
        70: "Custom actions with Voice Control",
        71: "APIs that work across assistive technologies",
        72: "Hide views with accessibilityElementsHidden",
        73: "isAccessibilityElement vs accessibilityElementsHidden",
        74: "Trap VoiceOver in overlays with accessibilityViewIsModal",
        75: "Move VoiceOver focus on modal present",
        76: "Move VoiceOver focus when UI expands",
        77: "Announce off-screen updates with notifications",
        78: "Queue VoiceOver announcements",
        79: "screenChanged vs layoutChanged notifications",
        80: "Compose accessibility labels from optionals",
        81: "Traverse children with shouldGroupAccessibilityChildren",
        82: "Fix traversal order with accessibilityElements",
        83: "Group a UILabel with its UISwitch",
        84: "Label switches in settings table cells",
        85: "Expand hit targets with accessibilityFrame",
        86: "Add context with accessibilityContainerType",
        87: "Announce tab bars and toolbars like Apple",
        88: "When to use semanticGroup containers",
        89: "Update accessibilityLabel when toggling",
        90: "When to tweak button accessibility labels",
        91: "Respond when VoiceOver turns on or off",
        92: "Create UIAccessibilityElement for custom drawing",
        93: "Group distant views with UIAccessibilityElement",
        94: "Make charts accessible with UIAccessibilityElement",
        95: "Explore charts with Audio Graphs (AXChart)",
        96: "Audio Graphs trends, outliers, and stats",
        97: "Customize taps with accessibilityActivationPoint",
        98: "Accessible chart color and contrast tips",
        99: "Group chart data into accessibility chunks",
        100: "Who invented VoiceOver?",
        101: "Mark optional data with AXCustomContent",
        102: "Set AXCustomContent importance for VoiceOver",
        103: "Tailor VoiceOver with accessibilityCustomContent",
        104: "Combine elements in SwiftUI accessibility",
        105: "SwiftUI accessibilityElement like UIKit grouping",
        106: "Prefer combine before accessibilityElement ignore",
        107: "Fix combined SwiftUI accessibility labels",
        108: "Build adjustable controls in SwiftUI",
        109: "SwiftUI contain mirrors semanticGroup",
        110: "Manage accessibility traits in SwiftUI",
        111: "Use disabled instead of notEnabled in SwiftUI",
        112: "Map custom views with accessibilityRepresentation",
        113: "Support Dynamic Type with text styles",
        114: "Dynamic Type sizes don't scale linearly",
        115: "Enable adjustsFontForContentSizeCategory",
        116: "Scale custom fonts with UIFontMetrics",
        117: "Adapt layouts for accessibility text sizes",
        118: "React to any content size category",
        119: "Flip stack axis for large Dynamic Type",
        120: "Use fewer columns with large Dynamic Type",
        121: "Switch Auto Layout constraints for large text",
        122: "Find ideal label width with readableContentGuide",
        123: "Space label baselines for Dynamic Type",
        124: "Let UIImageView scale for accessibility sizes",
        125: "Tap and hold bar items at large text sizes",
        126: "Add Large Content Viewer to custom bars",
        127: "Configure Large Content Viewer titles and images",
        128: "Keep large content icons crisp with PDFs",
        129: "Support Dynamic Type in WKWebView CSS",
        130: "Scale custom UI with UIFontMetrics",
        131: "Handle magic tap in SwiftUI",
        132: "My NSSpain talk recording is online",
        133: "Great NSSpain accessibility talks to watch",
        134: "Handle perform escape in SwiftUI",
        135: "Catch missing image labels with SwiftLint",
        136: "Raise label line limits for large text",
        137: "Follow Accessible Mobile Apps Weekly",
        138: "Watch for content size category changes",
        139: "Respect iOS accessibility settings in code",
        140: "React when accessibility settings change",
        141: "Don't rely on color alone",
        142: "Listen to articles with Speak Screen",
        143: "Adapt UI when Reduce Transparency is on",
        144: "Tone down animations for Reduce Motion",
        145: "Detect Bold Text with UIAccessibility",
        146: "Ship bolder fonts when Bold Text is on",
        147: "Make icons work with Bold Text",
        148: "Help Voice Control guess button names",
        149: "Keep media readable with Smart Invert",
        150: "Books that level up your accessibility game",
        151: "Reinforce warnings with haptic feedback",
        152: "Takeaways from a11yTO for iOS developers",
        153: "More takeaways from a11yTO",
        154: "Use haptics when tasks fail",
        155: "Celebrate success with haptic feedback",
        156: "Test VoiceOver behind Screen Curtain",
        157: "Triple-click into accessibility shortcuts",
        158: "Put accessibility testing in Control Centre",
        159: "Change Dynamic Type per app quickly",
        160: "Turn on larger accessibility text sizes",
        161: "Show what VoiceOver says on screen",
        162: "Turn on VoiceOver with Siri",
        163: "Xcode's Accessibility Inspector, explained",
        164: "Inspect labels, traits, and actions",
        165: "Run accessibility audits in the simulator",
        166: "Flip accessibility settings in Inspector",
        167: "Calculate color contrast in Inspector",
        168: "Override accessibility settings while debugging",
        169: "Bump text size fast in Simulator",
        170: "Try Full Keyboard Access in Simulator",
        171: "Find weak labels with Show names",
        172: "Accessibility is caring, not just APIs",
        173: "Braille Scanner reads braille with ML",
        174: "Spotlight: Jordi Bruin and Navi",
        175: "Input labels help keyboard users too",
        176: "Set accessibility traits in Interface Builder",
        177: "Preview accessibility before you run",
        178: "Inspect other apps with Accessibility Inspector",
        179: "Watch VoiceOver events in Inspector",
        180: "SwiftUI's Accessibility Inspector panel",
        181: "Preview Dynamic Type with SwiftUI variants",
        182: "ScreenReader: learn VoiceOver gestures playfully",
        183: "36 seconds that changed everything",
        184: "Bonus content from 36 Seconds",
        185: "Zoom gestures on iOS",
        186: "What Zoom testing reveals in your UI",
        187: "High Contrast variants in Color Sets",
        188: "High Contrast image variants in Assets",
        189: "Test Increase Contrast beyond color tweaks",
        190: "Be My Eyes: sighted help when you need it",
        191: "Stress-test UI with Double-length Pseudolanguage",
        192: "Increase Contrast for colors defined in code",
        193: "System semantic colors and contrast",
        194: "Essential VoiceOver gestures to learn first",
        195: "VoiceOver on iPhone without a Home button",
        196: "The VoiceOver Rotor and power gestures",
        197: "Unlabelled elements: the issue I see most often",
        198: "Writing better accessibility labels",
        199: "Mark headings with the header trait",
        200: "Don't miss visual cues in accessibility labels",
        201: "Alt text and decorative images",
        202: "The button trait for tappable views",
        203: "Group elements to ease VoiceOver navigation",
        204: "isAccessibilityElement and nested controls",
        205: "Custom actions for hidden interactions",
        206: "Common UISwitch accessibility mistakes",
        207: "Keep VoiceOver in modals with isModal",
        208: "Announce toasts and on-screen changes",
        209: "Accessibility for custom UI components",
        210: "Xcode and iOS color contrast tools",
        211: "Keep touch targets at 44 points",
        212: "Combine color, haptics, and icons",
        213: "Fix accessibility traversal order",
        214: "Set accessibility traits on custom controls",
        215: "accessibilityUserInputLabels for Voice Control",
        216: "Respect Reduce Motion in animations",
        217: "React to accessibility settings changes",
        218: "Support accessibility Dynamic Type sizes",
        219: "Reflow layout for large text sizes",
        220: "Test manually with assistive technologies",
        221: "Screen Curtain and VoiceOver shortcuts",
        222: "AssistiveTouch on Apple Watch",
        223: "Double-pinch quick actions on Watch",
        224: "We have one job: make our apps work",
        225: "Support both orientations when you can",
        226: "Let users add alt text when sharing",
        227: "accessibilitySortPriority for VoiceOver order",
        228: "Set up your device for a11y testing",
        229: "accessibilityElement(children:) in SwiftUI",
        230: "Sydney Cocoaheads' spectacular GAAD event",
        231: "keyboardShortcut modifier in SwiftUI",
        232: "UIKeyCommand shortcuts in UIKit",
        233: "Multiple inputs for accessible spatial experiences",
    ]
}
